name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install Cordova
        run: |
          npm install -g cordova
          cordova telemetry off
      
      - name: Build APK (New Path)
        run: |
          export NODE_OPTIONS=--max_old_space_size=6144
          cordova platform add android@12.0.0
          cordova build android --release -- --packageType=apk
          ls -la platforms/android/app/build/outputs/apk/release/  # Debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gymtracker-apk
          path: platforms/android/app/build/outputs/apk/**/*.apk  # Nueva ruta universal
          retention-days: 1
